### ISSUE TITLE
Error on build after cloning the repo

### ISSUE THREAD

**Issue by toxicafunk** [ScalaConsultants/panopticon-tui#32]
SO I cloned the repo and

```
panopticon-tui]$ cargo build
error: failed to parse lock file at: /home/enrs/src/rust/panopticon-tui/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

deleting `Cargo.lock` and then building seems to work.

**Comment by jczuchnowski** [comment]
@toxicafunk could you post your current `Cargo.lock` file as well as versions of `cargo` and `rustc` ?

**Comment by toxicafunk** [comment]
Ok, so it was an issue with my cargo/rustc version. My bad!
