### ISSUE TITLE
jmx-rust and j4rs dependency

### ISSUE THREAD

**Issue by astonbitecode** [ScalaConsultants/panopticon-tui#39]
Hi there! I read [this notice](https://github.com/ScalaConsultants/panopticon-tui#%EF%B8%8F-macos-and-libjvmdylib) in the README and I think that this is because of a [j4rs issue](https://github.com/astonbitecode/j4rs/issues/13) that is resolved in the latest releases.

I guess there wouldn't be any issue if `jmx-rust` crate upgrades to the latest j4rs version. So, maybe you could try to verify that this is indeed the problem and then contact the maintainer for an upgrade?

**Comment by vpavkin** [comment]
@astonbitecode thanks for a great suggestion, that would be awesome. I'll try sending a PR to jmx-rust and see where it goes :+1:

**Comment by astonbitecode** [comment]
Good news... It seems that the maintainer proceeded (by himself?) with the upgrade. Now the [jmx-0.2.1](https://crates.io/crates/jmx/0.2.1) has the latest j4rs as dependency. 

I guess you can just give it a check now!

**Comment by vpavkin** [comment]
Right, @astonbitecode. I even made a release [0.2.1 ](https://github.com/ScalaConsultants/panopticon-tui/releases/tag/v0.2.1) of panopticon already. Sorry, got caught up in other stuff and forgot to let you know

**Comment by astonbitecode** [comment]
That's great. Thanks
